rm -rf ./did/shacl/CVS
rm -rf ./did/shex/CVS
rm -rf ./did/vocab/CVS
rm -rf ./dx/connegp/CVS
rm -rf ./dx/connegp/profile/CVS
rm -rf ./dx/prof/CVS
rm -rf ./dx/prof/role/CVS
rm -rf ./entailment/data/CVS
rm -rf ./epub/2007/CVS
rm -rf ./epub/2007/opf/CVS
rm -rf ./epub/2007/ops/CVS
rm -rf ./epub/2008/CVS
rm -rf ./epub/2008/embedding/CVS
rm -rf ./epub/2013/CVS
rm -rf ./epub/2013/metadata/CVS
rm -rf ./epub/2016/CVS
rm -rf ./epub/2016/encryption/CVS
rm -rf ./formats/data/CVS
rm -rf ./formats/vocab-data/CVS
rm -rf ./iana/link-relations/CVS
rm -rf ./iana/media-types/CVS
rm -rf ./iana/media-types/application/CVS
rm -rf ./iana/media-types/audio/CVS
rm -rf ./iana/media-types/font/CVS
rm -rf ./iana/media-types/image/CVS
rm -rf ./iana/media-types/message/CVS
rm -rf ./iana/media-types/model/CVS
rm -rf ./iana/media-types/multipart/CVS
rm -rf ./iana/media-types/text/CVS
rm -rf ./iana/media-types/video/CVS
rm -rf ./iana/person/CVS
rm -rf ./iana/vocab/CVS
rm -rf ./ma-ont-old/examples/CVS
rm -rf ./ma-ont-old/examples/example3-content/CVS
rm -rf ./odrl/2/CVS
rm -rf ./owl-profile/data/CVS
rm -rf ./pim/fin/CVS
rm -rf ./pub-schema/audiobooks/CVS
rm -rf ./pub-schema/audiobooks/module/CVS
rm -rf ./pub-schema/manifest/CVS
rm -rf ./pub-schema/manifest/module/CVS
rm -rf ./sosa/oboe/CVS
rm -rf ./sosa/om/CVS
rm -rf ./sosa/prov/CVS
rm -rf ./sosa/sampling/CVS
rm -rf ./sosa/test/CVS
rm -rf ./ssn/dul/CVS
rm -rf ./ssn/ext/CVS
rm -rf ./ssn/systems/CVS
rm -rf ./time/gregorian/CVS
rm -rf ./ttml/extension/CVS
rm -rf ./ttml/feature/CVS
rm -rf ./ttml/profile/CVS
rm -rf ./ttml/profile/imsc1/CVS
rm -rf ./ttml/profile/imsc1/extension/CVS
rm -rf ./ttml/profile/imsc1/image/CVS
rm -rf ./ttml/profile/imsc1/text/CVS
rm -rf ./wsdl/style/CVS
